### ISSUE TITLE
wrong title names in the search results of the subtitles

### ISSUE THREAD

**Issue by EPiC-APOC** [romanvm/service.addic7ed#3] opened 2019-01-18 13:42 UTC
The title names of the subtitles are wrong in the search results (for instance in Seren addon etc), they show up like 'Amzn.web-DLetcetc, retail sub etcetc' and not like in any relation to the (real) series name what so ever, I hope you understand what I mean?

Does work awesome for the rest, thank you very much for that, really appreciated.

**Comment by romanvm** [comment] 2019-01-18 21:29
Please provide detailed description of your issue, including full [debug log](https://kodi.wiki/view/Log_file/Advanced).

Also I have no idea what this "Seren addon" is, but this addon only works with addons that populate extended information about episodes being played.

**Comment by romanvm** [comment] 2019-02-14 05:20
I'm closing this issue because of no follow-up.

**Closed as completed by romanvm** 2019-02-14 05:20 UTC

**Comment by EPiC-APOC** [comment] 2019-03-15 13:18
Sorry, I've really been busy and forgot all about it, the problem does still exist though and in multiple addons, this is how it looks when I search for subtitles with this Addic7ed addon (in Krypton):
![howitlooks](https://user-images.githubusercontent.com/16701549/54433792-fa996200-472c-11e9-9c62-96ca49a1fb65.png)

Subtitles do work excellent, it's just hard to choose as you can see _lol_ **;)**

**Comment by EPiC-APOC** [comment] 2019-04-25 11:44
@romanvm is it possible to re-open this issue? I can give you a follow-up if needed. 
As you can see in the picture above (https://github.com/romanvm/service.addic7ed/issues/3?_pjax=%23js-repo-pjax-container#issuecomment-473282559) the description of the titles is (still) wrong/weird.

**Comment by romanvm** [comment] 2019-04-25 12:23
And you still haven't provided the requested information. 
As for descriptions, they are taken from "Version" info on Addic7ed.com. There are no other descriptions on episode pages on Addic7ed.com that allow to distinguish different version of subtitles. If the addon picks wrong information from Addic7ed pages, then please provide detailed examples of what you think should be scraped from the pages as descriptions for specific subs. If you don't like subs descriptions in general, please address your complaints to Addic7ed.com. This addon does not invent any info by itself, it takes what is published on Addic7ed.com.

**Comment by EPiC-APOC** [comment] 2019-05-01 08:42
> 
> 
> And you still haven't provided the requested information.
> As for descriptions, they are taken from "Version" info on Addic7ed.com. There are no other descriptions on episode pages on Addic7ed.com that allow to distinguish different version of subtitles. If the addon picks wrong information from Addic7ed pages, then please provide detailed examples of what you think should be scraped from the pages as descriptions for specific subs. If you don't like subs descriptions in general, please address your complaints to Addic7ed.com. This addon does not invent any info by itself, it takes what is published on Addic7ed.com.

but the earlier addic7ed addon did (and does) also show the working title of the current serie being search I mean, now it does not, sometimes a series title is to common so you also get al lot of misplaced serie titles, but now you cannot see that because only the info is stated in de picture is provided. IF it also showed the serie title one could see what what supplied results are wrong. I hope you can understand what I actually mean? So nothing to invent but also show the series title as supplied through the search results I mean, then you can actually spot wrong subtitles which now is impossible (unless you download first).

**Comment by EPiC-APOC** [comment] 2019-05-01 08:49
if you need I can supply a follow-up, but I thought I'd explain the situation 1st to you, the series title itself is missing is the "problem" not the description info itself. With kind regards.

**Comment by romanvm** [comment] 2019-05-01 14:10
What do you mean by "series title"? And how will it help you to pick correct subtitles, considering that they belong to the same episode with the same title? In this case a filename would help, but the filename label is set by Kodi, not by the addon. Also I don't see anything wrong on your screenshot. This is how Addic7ed.com displays information about different versions of subtitles for the same episode and there is nothing I can do about that.

I'm asking you for the last time to provide proper detailed description of your issue - what is the expected result and what is the actual result? And please don' forget a debug log. Otherwise I cannot help you.

**Comment by EPiC-APOC** [comment] 2019-05-17 13:28
I mean as you can see in the screenshot earlier the 'working title' of the 'serie episode' is not visible...
Sometimes the episode name (series title?) is set really bad (when it's just one word for instance) and then you get a lot of results and also wrong results, like episodes from other series. This you cannot see now (wrong returned search results) because what is listed on screen is the "technical" subtitle info. 
=> Everything but the title/name of the series episode I mean. 
In such case it would help that the result list also showed the names of the episodes  which are returned as search result.

for instance, Addi7ed results:
![addi7ed](https://user-images.githubusercontent.com/16701549/57931068-ebaf6700-78b7-11e9-8280-911f60d0899c.png)

compared to Opensubs:
![opensubs](https://user-images.githubusercontent.com/16701549/57931073-ee11c100-78b7-11e9-9e77-315b7ea9cdfa.png)
Here you can see what exactly is returned, so you could filter wrong episode names

**Comment by romanvm** [comment] 2019-05-17 14:53
Subtitle names are taken from Addic7ed.com as is. Period. The titles that you see on the second screenshot are taken from the respective site and correspond to episode file name as it was released by the respective release group. Again, Addic7ed.com does not provide such info If you don't like what they display on the site - address your complaints to them. I cannot invent information that is not there.

If this addon finds wrong subtitles on Addic7ed.com, it is a separate issue that needs to be treated separately. If this is the case, please open a separate ticket with detailed description of the issue and (important!) a [Kodi debug log](https://kodi.wiki/view/Log_file/Easy) recorded while the issue is happening.

Also I need to note that this subtitle addon relies on correct information about a videofile being played. If some video addons do not provide such information, again, this is not the problem of this addon.
